#!/usr/bin/env python3
"""Convert binary assets into C header files for embedding."""

import sys
import os


def bin_to_c_array(data: bytes, var_name: str) -> str:
    """Convert binary data to a C const unsigned char array."""
    lines = [f"// Auto-generated by embed_assets.py", f"// Source: embedded binary data", f""]
    lines.append(f"static const unsigned char {var_name}_data[] = {{")

    hex_values = []
    for i, byte in enumerate(data):
        if i > 0 and i % 16 == 0:
            lines.append("    " + ", ".join(hex_values) + ",")
            hex_values = []
        hex_values.append(f"0x{byte:02x}")

    if hex_values:
        lines.append("    " + ", ".join(hex_values))

    lines.append(f"}};")
    lines.append(f"static const unsigned int {var_name}_size = sizeof({var_name}_data);")
    lines.append("")
    return "\n".join(lines)


def process_file(file_path: str, var_name: str) -> str:
    """Read a file and return C array declaration."""
    with open(file_path, "rb") as f:
        data = f.read()
    return bin_to_c_array(data, var_name)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output_header> <input_file> [var_name] ...")
        sys.exit(1)

    output_path = sys.argv[1]
    entries = sys.argv[2:]

    header = "#pragma once\n\n"
    header += "// Auto-generated by embed_assets.py - DO NOT EDIT\n"
    header += "// Contains embedded binary assets\n\n"
    header += "#include <cstddef>\n\n"

    # Process pairs of (file, var_name)
    i = 0
    while i < len(entries):
        file_path = entries[i]
        var_name = entries[i + 1] if i + 1 < len(entries) else os.path.splitext(os.path.basename(file_path))[0]
        var_name = var_name.replace("-", "_").replace(".", "_")
        header += process_file(file_path, var_name)
        i += 2

    # Add helper function
    header += """
// Helper: Load font from embedded data
inline Font LoadFontFromMemory(const unsigned char* data, unsigned int size, int fontSize, int* codepoints, int codepointCount) {
    Font font = {};
    if (data && size > 0) {
        font = LoadFontFromMemory(".ttf", data, size, fontSize, codepoints, codepointCount);
    }
    return font;
}
"""

    with open(output_path, "w") as f:
        f.write(header)

    print(f"Generated {output_path} with {len(entries) // 2} embedded asset(s)")


if __name__ == "__main__":
    main()
