name: build

on:
  push:
  pull_request:

jobs:
  local-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++ clang-format clang-tidy libcurl4-openssl-dev libsdl2-dev nlohmann-json3-dev libfmt-dev libspdlog-dev
      - name: Validate
        run: make -f Makefile-cpp verify
